name: CI

on:
  push:
    branches:
      - "main"
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Cache node_modules
        id: cache-node_modules
        uses: actions/cache@v2
        with:
          path: node_modules
          key: node_modules-${{ hashFiles('package.json', 'package-lock.json') }}

      - name: Cache ~/.elm
        uses: actions/cache@v2
        with:
          path: ~/.elm
          key: elm-${{ hashFiles('elm.json') }}

      - name: npm ci
        if: steps.cache-node_modules.outputs.cache-hit != 'true'
        env:
          NO_ELM_TOOLING_INSTALL: 1
        run: npm ci

      - name: elm-tooling install
        run: npx --no-install elm-tooling install

      - name: elm make
        run: git ls-files src | xargs elm make

      - name: elm-test
        run: npx --no-install elm-test

      - name: elm-format
        run: npx --no-install elm-format --validate src tests
